CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  passwd VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_rooms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_name VARCHAR(255) NOT NULL UNIQUE,
  user_owner_id INTEGER NOT NULL,

  FOREIGN KEY(user_owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS room_membership (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);
